/* A Bison parser, made by GNU Bison 3.0.4.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015 Free Software Foundation, Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output.  */
#define YYBISON 1

/* Bison version.  */
#define YYBISON_VERSION "3.0.4"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* Copy the first part of user declarations.  */
#line 8 "parser.y" /* yacc.c:339  */

#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include "bash.h"

/* some internal files generated by bison */
int yylex();
void yyerror(const char *s,...);
void yywarn(const char *s,...);

// Checks for invalid i/o redirection and throws an error if it finds anything bad
void check_ioredir(struct io_redir *optredir);

// Takes a linked list of io_redir objects and returns the first one it finds with the right redirect type
struct io_redir *find_iofile(struct io_redir *optredir, int type);

// Takes a string in the form of 'something=something' and assigns an environment variable
void AssignVar(char *string);

// Prints the prompt for the user
void Prompt();

// Removes the enclosing quotes from a string, double or single
char *DelQuotes(char *string);

// Checks a string to see if it can expand any environment variables inside it and returns the expanded version
char *VarExpand(char *string);

// Mimics the getenv system call, but checks the global vars array instead
char *mygetenv(char *name);

// Function for executing for loops
void doForLoop(struct loopfor *myfor);

// Function for executing while loops
void doWhileLoop(struct loopwhile *mywhile);

// Same thing as VarExpand, but doesn't check for single quotes and expands variables regardless
char *VarExpand2(char *string);


/* include debugging code, in case we want it */
#define YYDEBUG 1

#define MAX_ARGS 100
#define MAX_PATHS 100
#define MAX_VARS 100

int lines = 1;
static int synerrors = 0;
int errorflag = 0;
int DEBUG = 1;
struct var vars[MAX_VARS];
int NEXT_OPEN_SPOT = 4;		// first four spots in vars array are reserved for HOME, PROMPT, DEBUG, and PATH in that order



#line 128 "parser.tab.c" /* yacc.c:339  */

# ifndef YY_NULLPTR
#  if defined __cplusplus && 201103L <= __cplusplus
#   define YY_NULLPTR nullptr
#  else
#   define YY_NULLPTR 0
#  endif
# endif

/* Enabling verbose error messages.  */
#ifdef YYERROR_VERBOSE
# undef YYERROR_VERBOSE
# define YYERROR_VERBOSE 1
#else
# define YYERROR_VERBOSE 0
#endif

/* In a future release of Bison, this section will be replaced
   by #include "parser.tab.h".  */
#ifndef YY_YY_PARSER_TAB_H_INCLUDED
# define YY_YY_PARSER_TAB_H_INCLUDED
/* Debug traces.  */
#ifndef YYDEBUG
# define YYDEBUG 1
#endif
#if YYDEBUG
extern int yydebug;
#endif

/* Token type.  */
#ifndef YYTOKENTYPE
# define YYTOKENTYPE
  enum yytokentype
  {
    EOLN = 258,
    PIPE = 259,
    INPUT = 260,
    CD = 261,
    SEMICOLON = 262,
    FOR = 263,
    WHILE = 264,
    IN = 265,
    DO = 266,
    DONE = 267,
    EXPORT = 268,
    OUTPUT = 269,
    OUTPUT_APPEND = 270,
    ERROUT = 271,
    ERROUT_APPEND = 272,
    WORD = 273,
    VAR = 274,
    VAREXPAND = 275
  };
#endif

/* Value type.  */
#if ! defined YYSTYPE && ! defined YYSTYPE_IS_DECLARED

union YYSTYPE
{
#line 71 "parser.y" /* yacc.c:355  */
 /* the types that we use in the tokens */
    char *string;
    struct command *pcmd;
	struct metacmd *pmetacmd;
	struct metacmdlist *pmetacmdlist;
	struct loopwhile *pwhileloop;
	struct loopfor *pforloop;
    struct args *pargs;
	struct io_redir *pio;
	struct loopfor *pfor;
	struct loopwhile *pwhile;
    int number;

#line 203 "parser.tab.c" /* yacc.c:355  */
};

typedef union YYSTYPE YYSTYPE;
# define YYSTYPE_IS_TRIVIAL 1
# define YYSTYPE_IS_DECLARED 1
#endif


extern YYSTYPE yylval;

int yyparse (void);

#endif /* !YY_YY_PARSER_TAB_H_INCLUDED  */

/* Copy the second part of user declarations.  */

#line 220 "parser.tab.c" /* yacc.c:358  */

#ifdef short
# undef short
#endif

#ifdef YYTYPE_UINT8
typedef YYTYPE_UINT8 yytype_uint8;
#else
typedef unsigned char yytype_uint8;
#endif

#ifdef YYTYPE_INT8
typedef YYTYPE_INT8 yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef YYTYPE_UINT16
typedef YYTYPE_UINT16 yytype_uint16;
#else
typedef unsigned short int yytype_uint16;
#endif

#ifdef YYTYPE_INT16
typedef YYTYPE_INT16 yytype_int16;
#else
typedef short int yytype_int16;
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif ! defined YYSIZE_T
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned int
# endif
#endif

#define YYSIZE_MAXIMUM ((YYSIZE_T) -1)

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif

#ifndef YY_ATTRIBUTE
# if (defined __GNUC__                                               \
      && (2 < __GNUC__ || (__GNUC__ == 2 && 96 <= __GNUC_MINOR__)))  \
     || defined __SUNPRO_C && 0x5110 <= __SUNPRO_C
#  define YY_ATTRIBUTE(Spec) __attribute__(Spec)
# else
#  define YY_ATTRIBUTE(Spec) /* empty */
# endif
#endif

#ifndef YY_ATTRIBUTE_PURE
# define YY_ATTRIBUTE_PURE   YY_ATTRIBUTE ((__pure__))
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# define YY_ATTRIBUTE_UNUSED YY_ATTRIBUTE ((__unused__))
#endif

#if !defined _Noreturn \
     && (!defined __STDC_VERSION__ || __STDC_VERSION__ < 201112)
# if defined _MSC_VER && 1200 <= _MSC_VER
#  define _Noreturn __declspec (noreturn)
# else
#  define _Noreturn YY_ATTRIBUTE ((__noreturn__))
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YYUSE(E) ((void) (E))
#else
# define YYUSE(E) /* empty */
#endif

#if defined __GNUC__ && 407 <= __GNUC__ * 100 + __GNUC_MINOR__
/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN \
    _Pragma ("GCC diagnostic push") \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")\
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# define YY_IGNORE_MAYBE_UNINITIALIZED_END \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif


#if ! defined yyoverflow || YYERROR_VERBOSE

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* ! defined yyoverflow || YYERROR_VERBOSE */


#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yytype_int16 yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (sizeof (yytype_int16) + sizeof (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYSIZE_T yynewbytes;                                            \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / sizeof (*yyptr);                          \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, (Count) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYSIZE_T yyi;                         \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  37
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   133

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  21
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  20
/* YYNRULES -- Number of rules.  */
#define YYNRULES  50
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  88

/* YYTRANSLATE[YYX] -- Symbol number corresponding to YYX as returned
   by yylex, with out-of-bounds checking.  */
#define YYUNDEFTOK  2
#define YYMAXUTOK   275

#define YYTRANSLATE(YYX)                                                \
  ((unsigned int) (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, without out-of-bounds checking.  */
static const yytype_uint8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20
};

#if YYDEBUG
  /* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_uint16 yyrline[] =
{
       0,   102,   102,   103,   106,   107,   108,   109,   112,   122,
     131,   132,   134,   133,   170,   169,   174,   175,   178,   184,
     190,   196,   201,   219,   227,   233,   238,   244,   248,   254,
     261,   268,   274,   281,   286,   295,   304,   313,   324,   431,
     437,   443,   451,   458,   463,   469,   476,   483,   490,   497,
     505
};
#endif

#if YYDEBUG || YYERROR_VERBOSE || 0
/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "$end", "error", "$undefined", "EOLN", "PIPE", "INPUT", "CD",
  "SEMICOLON", "FOR", "WHILE", "IN", "DO", "DONE", "EXPORT", "OUTPUT",
  "OUTPUT_APPEND", "ERROUT", "ERROUT_APPEND", "WORD", "VAR", "VAREXPAND",
  "$accept", "input", "lines", "forloop", "whileloop", "oneline", "$@1",
  "$@2", "eoln", "line", "variable", "assignment", "chdir", "metacmdlist",
  "metacmd", "cmd", "loopargs", "args", "arg", "optredir", YY_NULLPTR
};
#endif

# ifdef YYPRINT
/* YYTOKNUM[NUM] -- (External) token number corresponding to the
   (internal) symbol number NUM (which must be that of a token).  */
static const yytype_uint16 yytoknum[] =
{
       0,   256,   257,   258,   259,   260,   261,   262,   263,   264,
     265,   266,   267,   268,   269,   270,   271,   272,   273,   274,
     275
};
# endif

#define YYPACT_NINF -45

#define yypact_value_is_default(Yystate) \
  (!!((Yystate) == (-45)))

#define YYTABLE_NINF -8

#define yytable_value_is_error(Yytable_value) \
  0

  /* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
     STATE-NUM.  */
static const yytype_int8 yypact[] =
{
      87,    13,   -45,   -15,     4,   -10,    14,    -3,    -3,    -3,
      -3,    25,   -45,   108,   108,   108,   -45,   -45,    13,    13,
       9,   -45,    -3,   -45,    16,   -45,   -45,   -45,    30,    13,
     -45,   -45,    11,    -3,    56,   -45,   -45,   -45,   -45,   -45,
     -45,    13,   -45,   -45,    24,   -45,    -3,    13,    14,   -45,
     -45,   -45,   -45,    27,    29,    31,    32,    34,    24,   -45,
     -45,    13,    -3,    14,   -45,    13,    56,    56,    56,    56,
      56,   -45,    42,   -45,    43,   -45,   -45,   -45,   -45,   -45,
     -45,    13,    13,    14,   -45,    44,    13,   -45
};

  /* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
     Performed when YYTABLE does not specify something else to do.  Zero
     means the default is an error.  */
static const yytype_uint8 yydefact[] =
{
       0,     0,    18,    29,    20,     0,    33,    43,    43,    25,
      26,     0,     2,     0,     0,     0,    16,    14,     0,     0,
      21,    17,    30,    19,     0,    36,    35,    37,     0,     0,
      34,    44,     0,    43,    50,    27,    28,     1,     5,     6,
       4,     0,    11,    10,     0,    31,     0,     0,    33,    23,
      12,    24,    42,     0,     0,     0,     0,     0,    38,    15,
      22,     0,    41,    33,    32,     0,    50,    50,    50,    50,
      50,    39,     0,    40,     0,    13,    45,    46,    47,    48,
      49,     0,     0,    33,     9,     0,     0,     8
};

  /* YYPGOTO[NTERM-NUM].  */
static const yytype_int8 yypgoto[] =
{
     -45,   -45,    23,     0,     3,   -45,   -45,   -45,    -1,   -30,
     -45,    -5,   -45,   -44,   -45,    -4,     5,     2,   -41,    63
};

  /* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
      -1,    11,    12,    13,    14,    15,    65,    41,    16,    17,
      50,    18,    19,    28,    29,    20,    61,    32,    33,    58
};

  /* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
     positive, shift that token.  If negative, reduce the rule whose
     number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int8 yytable[] =
{
      21,    27,    30,    22,    64,    62,    25,    23,    24,    26,
      34,    35,    36,    44,    60,    31,     2,    42,    43,    74,
       4,    62,     5,     6,    45,    37,    46,    51,    48,    49,
       9,    10,     8,     9,    10,    52,    38,    39,    40,    85,
      59,    47,     8,    27,    30,    66,    63,    67,    25,    68,
      69,    26,    70,    81,    71,    82,    86,     0,    27,    30,
      72,    53,     0,    25,    75,     0,    26,    73,     0,     0,
      54,    55,    56,    57,     0,     0,     0,     0,    27,    30,
      83,    84,     0,    25,     0,    87,    26,    -3,     1,     0,
       2,     0,     0,     3,     4,     5,     6,     0,     0,     0,
       7,     0,     0,     0,     0,     8,     9,    10,    -7,     1,
       0,     2,     0,     0,     3,     4,     5,     6,     0,     0,
       0,     7,     0,     0,     0,     0,     8,     9,    10,    76,
      77,    78,    79,    80
};

static const yytype_int8 yycheck[] =
{
       1,     6,     6,    18,    48,    46,     6,     3,    18,     6,
       8,     9,    10,     4,    44,    18,     3,    18,    19,    63,
       7,    62,     8,     9,    22,     0,    10,    32,    29,    18,
      19,    20,    18,    19,    20,    33,    13,    14,    15,    83,
      41,    11,    18,    48,    48,    18,    47,    18,    48,    18,
      18,    48,    18,    11,    58,    12,    12,    -1,    63,    63,
      61,     5,    -1,    63,    65,    -1,    63,    62,    -1,    -1,
      14,    15,    16,    17,    -1,    -1,    -1,    -1,    83,    83,
      81,    82,    -1,    83,    -1,    86,    83,     0,     1,    -1,
       3,    -1,    -1,     6,     7,     8,     9,    -1,    -1,    -1,
      13,    -1,    -1,    -1,    -1,    18,    19,    20,     0,     1,
      -1,     3,    -1,    -1,     6,     7,     8,     9,    -1,    -1,
      -1,    13,    -1,    -1,    -1,    -1,    18,    19,    20,    66,
      67,    68,    69,    70
};

  /* YYSTOS[STATE-NUM] -- The (internal number of the) accessing
     symbol of state STATE-NUM.  */
static const yytype_uint8 yystos[] =
{
       0,     1,     3,     6,     7,     8,     9,    13,    18,    19,
      20,    22,    23,    24,    25,    26,    29,    30,    32,    33,
      36,    29,    18,     3,    18,    24,    25,    32,    34,    35,
      36,    18,    38,    39,    38,    38,    38,     0,    23,    23,
      23,    28,    29,    29,     4,    38,    10,    11,    29,    18,
      31,    32,    38,     5,    14,    15,    16,    17,    40,    29,
      30,    37,    39,    29,    34,    27,    18,    18,    18,    18,
      18,    36,    29,    37,    34,    29,    40,    40,    40,    40,
      40,    11,    12,    29,    29,    34,    12,    29
};

  /* YYR1[YYN] -- Symbol number of symbol that rule YYN derives.  */
static const yytype_uint8 yyr1[] =
{
       0,    21,    22,    22,    23,    23,    23,    23,    24,    25,
      26,    26,    27,    26,    28,    26,    26,    26,    29,    29,
      29,    30,    30,    31,    31,    32,    32,    32,    32,    33,
      33,    33,    34,    34,    35,    35,    35,    35,    36,    36,
      37,    37,    38,    38,    39,    40,    40,    40,    40,    40,
      40
};

  /* YYR2[YYN] -- Number of symbols on the right hand side of rule YYN.  */
static const yytype_uint8 yyr2[] =
{
       0,     2,     1,     0,     2,     2,     2,     0,    10,     7,
       2,     2,     0,     5,     0,     3,     1,     2,     1,     2,
       1,     1,     3,     1,     1,     1,     1,     2,     2,     1,
       2,     3,     3,     0,     1,     1,     1,     1,     3,     4,
       2,     1,     2,     0,     1,     3,     3,     3,     3,     3,
       0
};


#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)
#define YYEMPTY         (-2)
#define YYEOF           0

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                  \
do                                                              \
  if (yychar == YYEMPTY)                                        \
    {                                                           \
      yychar = (Token);                                         \
      yylval = (Value);                                         \
      YYPOPSTACK (yylen);                                       \
      yystate = *yyssp;                                         \
      goto yybackup;                                            \
    }                                                           \
  else                                                          \
    {                                                           \
      yyerror (YY_("syntax error: cannot back up")); \
      YYERROR;                                                  \
    }                                                           \
while (0)

/* Error token number */
#define YYTERROR        1
#define YYERRCODE       256



/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)

/* This macro is provided for backward compatibility. */
#ifndef YY_LOCATION_PRINT
# define YY_LOCATION_PRINT(File, Loc) ((void) 0)
#endif


# define YY_SYMBOL_PRINT(Title, Type, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Type, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*----------------------------------------.
| Print this symbol's value on YYOUTPUT.  |
`----------------------------------------*/

static void
yy_symbol_value_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
{
  FILE *yyo = yyoutput;
  YYUSE (yyo);
  if (!yyvaluep)
    return;
# ifdef YYPRINT
  if (yytype < YYNTOKENS)
    YYPRINT (yyoutput, yytoknum[yytype], *yyvaluep);
# endif
  YYUSE (yytype);
}


/*--------------------------------.
| Print this symbol on YYOUTPUT.  |
`--------------------------------*/

static void
yy_symbol_print (FILE *yyoutput, int yytype, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyoutput, "%s %s (",
             yytype < YYNTOKENS ? "token" : "nterm", yytname[yytype]);

  yy_symbol_value_print (yyoutput, yytype, yyvaluep);
  YYFPRINTF (yyoutput, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yytype_int16 *yybottom, yytype_int16 *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yytype_int16 *yyssp, YYSTYPE *yyvsp, int yyrule)
{
  unsigned long int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %lu):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       yystos[yyssp[yyi + 1 - yynrhs]],
                       &(yyvsp[(yyi + 1) - (yynrhs)])
                                              );
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
# define YY_SYMBOL_PRINT(Title, Type, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif


#if YYERROR_VERBOSE

# ifndef yystrlen
#  if defined __GLIBC__ && defined _STRING_H
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
yystrlen (const char *yystr)
{
  YYSIZE_T yylen;
  for (yylen = 0; yystr[yylen]; yylen++)
    continue;
  return yylen;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined __GLIBC__ && defined _STRING_H && defined _GNU_SOURCE
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
yystpcpy (char *yydest, const char *yysrc)
{
  char *yyd = yydest;
  const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif

# ifndef yytnamerr
/* Copy to YYRES the contents of YYSTR after stripping away unnecessary
   quotes and backslashes, so that it's suitable for yyerror.  The
   heuristic is that double-quoting is unnecessary unless the string
   contains an apostrophe, a comma, or backslash (other than
   backslash-backslash).  YYSTR is taken from yytname.  If YYRES is
   null, do not copy; instead, return the length of what the result
   would have been.  */
static YYSIZE_T
yytnamerr (char *yyres, const char *yystr)
{
  if (*yystr == '"')
    {
      YYSIZE_T yyn = 0;
      char const *yyp = yystr;

      for (;;)
        switch (*++yyp)
          {
          case '\'':
          case ',':
            goto do_not_strip_quotes;

          case '\\':
            if (*++yyp != '\\')
              goto do_not_strip_quotes;
            /* Fall through.  */
          default:
            if (yyres)
              yyres[yyn] = *yyp;
            yyn++;
            break;

          case '"':
            if (yyres)
              yyres[yyn] = '\0';
            return yyn;
          }
    do_not_strip_quotes: ;
    }

  if (! yyres)
    return yystrlen (yystr);

  return yystpcpy (yyres, yystr) - yyres;
}
# endif

/* Copy into *YYMSG, which is of size *YYMSG_ALLOC, an error message
   about the unexpected token YYTOKEN for the state stack whose top is
   YYSSP.

   Return 0 if *YYMSG was successfully written.  Return 1 if *YYMSG is
   not large enough to hold the message.  In that case, also set
   *YYMSG_ALLOC to the required number of bytes.  Return 2 if the
   required number of bytes is too large to store.  */
static int
yysyntax_error (YYSIZE_T *yymsg_alloc, char **yymsg,
                yytype_int16 *yyssp, int yytoken)
{
  YYSIZE_T yysize0 = yytnamerr (YY_NULLPTR, yytname[yytoken]);
  YYSIZE_T yysize = yysize0;
  enum { YYERROR_VERBOSE_ARGS_MAXIMUM = 5 };
  /* Internationalized format string. */
  const char *yyformat = YY_NULLPTR;
  /* Arguments of yyformat. */
  char const *yyarg[YYERROR_VERBOSE_ARGS_MAXIMUM];
  /* Number of reported tokens (one for the "unexpected", one per
     "expected"). */
  int yycount = 0;

  /* There are many possibilities here to consider:
     - If this state is a consistent state with a default action, then
       the only way this function was invoked is if the default action
       is an error action.  In that case, don't check for expected
       tokens because there are none.
     - The only way there can be no lookahead present (in yychar) is if
       this state is a consistent state with a default action.  Thus,
       detecting the absence of a lookahead is sufficient to determine
       that there is no unexpected or expected token to report.  In that
       case, just report a simple "syntax error".
     - Don't assume there isn't a lookahead just because this state is a
       consistent state with a default action.  There might have been a
       previous inconsistent state, consistent state with a non-default
       action, or user semantic action that manipulated yychar.
     - Of course, the expected token list depends on states to have
       correct lookahead information, and it depends on the parser not
       to perform extra reductions after fetching a lookahead from the
       scanner and before detecting a syntax error.  Thus, state merging
       (from LALR or IELR) and default reductions corrupt the expected
       token list.  However, the list is correct for canonical LR with
       one exception: it will still contain any token that will not be
       accepted due to an error action in a later state.
  */
  if (yytoken != YYEMPTY)
    {
      int yyn = yypact[*yyssp];
      yyarg[yycount++] = yytname[yytoken];
      if (!yypact_value_is_default (yyn))
        {
          /* Start YYX at -YYN if negative to avoid negative indexes in
             YYCHECK.  In other words, skip the first -YYN actions for
             this state because they are default actions.  */
          int yyxbegin = yyn < 0 ? -yyn : 0;
          /* Stay within bounds of both yycheck and yytname.  */
          int yychecklim = YYLAST - yyn + 1;
          int yyxend = yychecklim < YYNTOKENS ? yychecklim : YYNTOKENS;
          int yyx;

          for (yyx = yyxbegin; yyx < yyxend; ++yyx)
            if (yycheck[yyx + yyn] == yyx && yyx != YYTERROR
                && !yytable_value_is_error (yytable[yyx + yyn]))
              {
                if (yycount == YYERROR_VERBOSE_ARGS_MAXIMUM)
                  {
                    yycount = 1;
                    yysize = yysize0;
                    break;
                  }
                yyarg[yycount++] = yytname[yyx];
                {
                  YYSIZE_T yysize1 = yysize + yytnamerr (YY_NULLPTR, yytname[yyx]);
                  if (! (yysize <= yysize1
                         && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
                    return 2;
                  yysize = yysize1;
                }
              }
        }
    }

  switch (yycount)
    {
# define YYCASE_(N, S)                      \
      case N:                               \
        yyformat = S;                       \
      break
      YYCASE_(0, YY_("syntax error"));
      YYCASE_(1, YY_("syntax error, unexpected %s"));
      YYCASE_(2, YY_("syntax error, unexpected %s, expecting %s"));
      YYCASE_(3, YY_("syntax error, unexpected %s, expecting %s or %s"));
      YYCASE_(4, YY_("syntax error, unexpected %s, expecting %s or %s or %s"));
      YYCASE_(5, YY_("syntax error, unexpected %s, expecting %s or %s or %s or %s"));
# undef YYCASE_
    }

  {
    YYSIZE_T yysize1 = yysize + yystrlen (yyformat);
    if (! (yysize <= yysize1 && yysize1 <= YYSTACK_ALLOC_MAXIMUM))
      return 2;
    yysize = yysize1;
  }

  if (*yymsg_alloc < yysize)
    {
      *yymsg_alloc = 2 * yysize;
      if (! (yysize <= *yymsg_alloc
             && *yymsg_alloc <= YYSTACK_ALLOC_MAXIMUM))
        *yymsg_alloc = YYSTACK_ALLOC_MAXIMUM;
      return 1;
    }

  /* Avoid sprintf, as that infringes on the user's name space.
     Don't have undefined behavior even if the translation
     produced a string with the wrong number of "%s"s.  */
  {
    char *yyp = *yymsg;
    int yyi = 0;
    while ((*yyp = *yyformat) != '\0')
      if (*yyp == '%' && yyformat[1] == 's' && yyi < yycount)
        {
          yyp += yytnamerr (yyp, yyarg[yyi++]);
          yyformat += 2;
        }
      else
        {
          yyp++;
          yyformat++;
        }
  }
  return 0;
}
#endif /* YYERROR_VERBOSE */

/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg, int yytype, YYSTYPE *yyvaluep)
{
  YYUSE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yytype, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YYUSE (yytype);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}




/* The lookahead symbol.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;


/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    int yystate;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus;

    /* The stacks and their tools:
       'yyss': related to states.
       'yyvs': related to semantic values.

       Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* The state stack.  */
    yytype_int16 yyssa[YYINITDEPTH];
    yytype_int16 *yyss;
    yytype_int16 *yyssp;

    /* The semantic value stack.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs;
    YYSTYPE *yyvsp;

    YYSIZE_T yystacksize;

  int yyn;
  int yyresult;
  /* Lookahead token as an internal (translated) token number.  */
  int yytoken = 0;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;

#if YYERROR_VERBOSE
  /* Buffer for error messages, and its allocated size.  */
  char yymsgbuf[128];
  char *yymsg = yymsgbuf;
  YYSIZE_T yymsg_alloc = sizeof yymsgbuf;
#endif

#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  yyssp = yyss = yyssa;
  yyvsp = yyvs = yyvsa;
  yystacksize = YYINITDEPTH;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY; /* Cause a token to be read.  */
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyss + yystacksize - 1 <= yyssp)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        YYSTYPE *yyvs1 = yyvs;
        yytype_int16 *yyss1 = yyss;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * sizeof (*yyssp),
                    &yyvs1, yysize * sizeof (*yyvsp),
                    &yystacksize);

        yyss = yyss1;
        yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyexhaustedlab;
# else
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        goto yyexhaustedlab;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yytype_int16 *yyss1 = yyss;
        union yyalloc *yyptr =
          (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
        if (! yyptr)
          goto yyexhaustedlab;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
                  (unsigned long int) yystacksize));

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;

/*-----------.
| yybackup.  |
`-----------*/
yybackup:

  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either YYEMPTY or YYEOF or a valid lookahead symbol.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = yytoken = YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);

  /* Discard the shifted token.  */
  yychar = YYEMPTY;

  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
        case 8:
#line 113 "parser.y" /* yacc.c:1646  */
    {
				(yyval.pforloop) = (struct loopfor *) malloc(sizeof(struct loopfor));
				(yyval.pforloop)->variable = (yyvsp[-8].string);
				(yyval.pforloop)->loopargs = (yyvsp[-6].pargs);
				(yyval.pforloop)->body = (yyvsp[-2].pmetacmdlist);
				doForLoop((yyval.pforloop));
			}
#line 1366 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 9:
#line 123 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pwhileloop) = (struct loopwhile *) malloc(sizeof(struct loopwhile));
					(yyval.pwhileloop)->condition = (yyvsp[-5].pmetacmdlist);
					(yyval.pwhileloop)->body = (yyvsp[-2].pmetacmdlist);
					doWhileLoop((yyval.pwhileloop));
				}
#line 1377 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 12:
#line 134 "parser.y" /* yacc.c:1646  */
    {
				printf("1%s\n", (yyvsp[0].string));
    			fflush(stdout);
				struct command *mycommand = (struct command *) malloc(sizeof(struct command));
				mycommand->command = "export";
				mycommand->pargs = (yyvsp[-1].pargs);
				struct args *current = (struct args *)malloc(sizeof(struct args));
				current = mycommand->pargs;
				mycommand->argc++;
				if (current != NULL)
				{
					while (current->next != NULL)
					{
						mycommand->argc++;
						current = current->next;
					}
					mycommand->argc++;
					current->next = (struct args *)malloc(sizeof(struct args));
					current->next->arg = (yyvsp[0].string);
					current->next->next = NULL;
					printf("%s\n", current->next->arg);
					fflush(stdout);
				}
				else
				{
					mycommand->pargs = (struct args *)malloc(sizeof(struct args));
					mycommand->pargs->arg = (yyvsp[0].string);
					mycommand->pargs->next = NULL;
					printf("2%s\n", mycommand->pargs->arg);
					fflush(stdout);
				}

				doline(mycommand, lines, errorflag, DEBUG);
			}
#line 1416 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 14:
#line 170 "parser.y" /* yacc.c:1646  */
    {
				doline((yyvsp[0].pcmd), lines, errorflag, DEBUG);
			}
#line 1424 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 18:
#line 179 "parser.y" /* yacc.c:1646  */
    {
				++lines;
				errorflag = 0;
				Prompt();
			}
#line 1434 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 19:
#line 185 "parser.y" /* yacc.c:1646  */
    {
				++lines;
				errorflag = 0;
				Prompt();
			}
#line 1444 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 20:
#line 191 "parser.y" /* yacc.c:1646  */
    {
				errorflag = 0;
			}
#line 1452 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 21:
#line 197 "parser.y" /* yacc.c:1646  */
    {
				(yyval.pcmd) = (yyvsp[0].pcmd);
				(yyval.pcmd)->nextpipe = NULL;
			}
#line 1461 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 22:
#line 202 "parser.y" /* yacc.c:1646  */
    {
				(yyval.pcmd) = (yyvsp[-2].pcmd);
				(yyval.pcmd)->nextpipe = (yyvsp[0].pcmd);

				/* Check for invalid redirects inside pipes */
				if(strcmp((yyvsp[-2].pcmd)->outfile, "<undirected>") != 0)
				{
					yyerror("Cannot redirect output inside a pipe");
				}

				if(strcmp((yyvsp[0].pcmd)->infile, "<undirected>") != 0)
				{
					yyerror("Cannot redirect input inside a pipe");
				}
			}
#line 1481 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 23:
#line 220 "parser.y" /* yacc.c:1646  */
    {
					char *var = (yyvsp[0].string);
					strcat(var, "=");
					strcat(var, mygetenv((yyvsp[0].string)));
					AssignVar(var);
					(yyval.string) = var;
				}
#line 1493 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 24:
#line 228 "parser.y" /* yacc.c:1646  */
    {
					(yyval.string) = (yyvsp[0].string);
				}
#line 1501 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 25:
#line 234 "parser.y" /* yacc.c:1646  */
    {
					AssignVar((yyvsp[0].string));
					(yyval.string) = (yyvsp[0].string);
				}
#line 1510 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 26:
#line 239 "parser.y" /* yacc.c:1646  */
    {
					if (DEBUG == 1) printf("VarExpand : %s\n", VarExpand((yyvsp[0].string)));
					AssignVar(VarExpand((yyvsp[0].string)));
					(yyval.string) = (yyvsp[0].string);
				}
#line 1520 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 27:
#line 245 "parser.y" /* yacc.c:1646  */
    {
					yyerror("Cannot put arguments after variable assignment!!");
				}
#line 1528 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 28:
#line 249 "parser.y" /* yacc.c:1646  */
    {
					yyerror("Cannot put arguments after variable assignment!!");
				}
#line 1536 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 29:
#line 255 "parser.y" /* yacc.c:1646  */
    {
				if (chdir(vars[0].value) != 0)		// vars[0].name = "HOME"
				{
					yyerror("Could not go to home directory");
				}
			}
#line 1547 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 30:
#line 262 "parser.y" /* yacc.c:1646  */
    {
				if (chdir(VarExpand((yyvsp[0].string))) != 0)
				{
					yyerror("Invalid directory : %s\n", VarExpand((yyvsp[0].string)));
				}
			}
#line 1558 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 31:
#line 269 "parser.y" /* yacc.c:1646  */
    {
				yyerror("Multiple args for cd is not allowed!!");
			}
#line 1566 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 32:
#line 275 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pmetacmdlist) = (struct metacmdlist *) malloc(sizeof(struct metacmdlist));
					(yyval.pmetacmdlist)->metacmd = (yyvsp[-2].pmetacmd);
					(yyval.pmetacmdlist)->next = (yyvsp[0].pmetacmdlist);
				}
#line 1576 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 33:
#line 281 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pmetacmdlist) = NULL;
				}
#line 1584 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 34:
#line 287 "parser.y" /* yacc.c:1646  */
    {
				if (DEBUG == 1) printf("im in metacmd : cmd\n");
				(yyval.pmetacmd) = (struct metacmd *) malloc(sizeof(struct metacmd));
				(yyval.pmetacmd)->cmd = (yyvsp[0].pcmd);
				(yyval.pmetacmd)->whileloop = NULL;
				(yyval.pmetacmd)->forloop = NULL;
				(yyval.pmetacmd)->var_assign = NULL;
			}
#line 1597 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 35:
#line 296 "parser.y" /* yacc.c:1646  */
    {
				if (DEBUG == 1) printf("im in metacmd : whileloop\n");
				(yyval.pmetacmd) = (struct metacmd *) malloc(sizeof(struct metacmd));
				(yyval.pmetacmd)->cmd = NULL;
				(yyval.pmetacmd)->whileloop = (yyvsp[0].pwhileloop);
				(yyval.pmetacmd)->forloop = NULL;
				(yyval.pmetacmd)->var_assign = NULL;
			}
#line 1610 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 36:
#line 305 "parser.y" /* yacc.c:1646  */
    {
				if (DEBUG == 1) printf("im in metacmd : forloop\n");
				(yyval.pmetacmd) = (struct metacmd *) malloc(sizeof(struct metacmd));
				(yyval.pmetacmd)->cmd = NULL;
				(yyval.pmetacmd)->whileloop = NULL;
				(yyval.pmetacmd)->forloop = (yyvsp[0].pforloop);
				(yyval.pmetacmd)->var_assign = NULL;
			}
#line 1623 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 37:
#line 314 "parser.y" /* yacc.c:1646  */
    {
				if (DEBUG == 1) printf("im in metacmd : assignment\n");
				(yyval.pmetacmd) = (struct metacmd *) malloc(sizeof(struct metacmd));
				(yyval.pmetacmd)->cmd = NULL;
				(yyval.pmetacmd)->whileloop = NULL;
				(yyval.pmetacmd)->forloop = NULL;
				(yyval.pmetacmd)->var_assign = (yyvsp[0].string);
			}
#line 1636 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 38:
#line 325 "parser.y" /* yacc.c:1646  */
    {
				/* Store the command and args inside command struct */
				(yyval.pcmd) = (struct command *) malloc(sizeof(struct command));
				(yyval.pcmd)->command = VarExpand((yyvsp[-2].string));
				(yyval.pcmd)->pargs = (yyvsp[-1].pargs);
				if ((yyvsp[-2].string)[0] == '/')
				{
					(yyval.pcmd)->abs_path = 1;
				}
				else
				{
					(yyval.pcmd)->abs_path = 0;
				}

				/* Get the length of the args linked list into argc */
				struct args *current = (struct args*) malloc(sizeof(struct args));
				current = (yyvsp[-1].pargs);
				int args_len = 1;
				while(current != NULL)
				{
					if (args_len <= MAX_ARGS)
					{
						args_len++;
						current = current->next;
					}
					else
					{
						yyerror("Too many args!!");
						break;
					}
				}
				(yyval.pcmd)->argc = args_len;

				/* Only check for io redirection if there is any */
				if((yyvsp[0].pio) != NULL)
				{
					/* Check for valid redirects */
					check_ioredir((yyvsp[0].pio));

					/* Use a temporary pointer to an io_redir object to load data into command */
					struct io_redir *temp = (struct io_redir*) malloc(sizeof(struct io_redir));
					
					/* Infile */
					temp = find_iofile((yyvsp[0].pio), 0);
					if(temp == NULL)
					{
						(yyval.pcmd)->infile = "<undirected>";
					}
					else
					{
						(yyval.pcmd)->infile = temp->file;
					}

					/* Outfile */
					temp = find_iofile((yyvsp[0].pio), 1);
					if(temp == NULL)
					{
						/* Check for output append */
						temp = find_iofile((yyvsp[0].pio), 2);
						if(temp == NULL)
						{
							(yyval.pcmd)->outfile = "<undirected>";
						}
						else
						{
							(yyval.pcmd)->outfile = temp->file;
							(yyval.pcmd)->output_append = 1;
						}
					}
					else
					{
						(yyval.pcmd)->outfile = temp->file;
						(yyval.pcmd)->output_append = 0;
					}

					/* Errfile */
					temp = find_iofile((yyvsp[0].pio), 3);
					if(temp == NULL)
					{
						/* Check for error append */
						temp = find_iofile((yyvsp[0].pio), 4);
						if(temp == NULL)
						{
							(yyval.pcmd)->errfile = "<undirected>";
						}
						else
						{
							(yyval.pcmd)->errfile = temp->file;
							(yyval.pcmd)->error_append = 1;
						}
					}
					else
					{
						(yyval.pcmd)->errfile = temp->file;
						(yyval.pcmd)->error_append = 0;
					}
				}
				else
				{
					(yyval.pcmd)->infile = "<undirected>";
					(yyval.pcmd)->outfile = "<undirected>";
					(yyval.pcmd)->errfile = "<undirected>";
					(yyval.pcmd)->output_append = 0;
					(yyval.pcmd)->error_append = 0;
				}
			}
#line 1747 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 39:
#line 432 "parser.y" /* yacc.c:1646  */
    {
				yyerror("Cannot include arguments past the optional i/o redirection");
			}
#line 1755 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 40:
#line 438 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pargs) = (struct args *) malloc(sizeof(struct args));
					(yyval.pargs)->arg = (yyvsp[-1].string);
					(yyval.pargs)->next = (yyvsp[0].pargs);
				}
#line 1765 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 41:
#line 444 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pargs) = (struct args *) malloc(sizeof(struct args));
					(yyval.pargs)->arg = (yyvsp[0].string);
					(yyval.pargs)->next = NULL;
				}
#line 1775 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 42:
#line 452 "parser.y" /* yacc.c:1646  */
    {
				(yyval.pargs) = (struct args *) malloc(sizeof(struct args));
				(yyval.pargs)->arg = (yyvsp[-1].string);
				(yyval.pargs)->next = (yyvsp[0].pargs);
			}
#line 1785 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 43:
#line 458 "parser.y" /* yacc.c:1646  */
    { 
				(yyval.pargs) = NULL;
			}
#line 1793 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 44:
#line 464 "parser.y" /* yacc.c:1646  */
    {
				(yyval.string) = VarExpand((yyvsp[0].string));
			}
#line 1801 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 45:
#line 470 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = (struct io_redir *) malloc(sizeof(struct io_redir));
					(yyval.pio)->redir_type = 0;
					(yyval.pio)->file = VarExpand((yyvsp[-1].string));
					(yyval.pio)->next = (yyvsp[0].pio);
				}
#line 1812 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 46:
#line 477 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = (struct io_redir *) malloc(sizeof(struct io_redir));
					(yyval.pio)->redir_type = 1;
					(yyval.pio)->file = VarExpand((yyvsp[-1].string));
					(yyval.pio)->next = (yyvsp[0].pio);
				}
#line 1823 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 47:
#line 484 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = (struct io_redir *) malloc(sizeof(struct io_redir));
					(yyval.pio)->redir_type = 2;
					(yyval.pio)->file = VarExpand((yyvsp[-1].string));
					(yyval.pio)->next = (yyvsp[0].pio);
				}
#line 1834 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 48:
#line 491 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = (struct io_redir *) malloc(sizeof(struct io_redir));
					(yyval.pio)->redir_type = 3;
					(yyval.pio)->file = VarExpand((yyvsp[-1].string));
					(yyval.pio)->next = (yyvsp[0].pio);
				}
#line 1845 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 49:
#line 498 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = (struct io_redir *) malloc(sizeof(struct io_redir));
					(yyval.pio)->redir_type = 4;
					(yyval.pio)->file = VarExpand((yyvsp[-1].string));
					(yyval.pio)->next = (yyvsp[0].pio);
				}
#line 1856 "parser.tab.c" /* yacc.c:1646  */
    break;

  case 50:
#line 505 "parser.y" /* yacc.c:1646  */
    {
					(yyval.pio) = NULL;
				}
#line 1864 "parser.tab.c" /* yacc.c:1646  */
    break;


#line 1868 "parser.tab.c" /* yacc.c:1646  */
      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", yyr1[yyn], &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTOKENS] + *yyssp;
  if (0 <= yystate && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTOKENS];

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYEMPTY : YYTRANSLATE (yychar);

  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
#if ! YYERROR_VERBOSE
      yyerror (YY_("syntax error"));
#else
# define YYSYNTAX_ERROR yysyntax_error (&yymsg_alloc, &yymsg, \
                                        yyssp, yytoken)
      {
        char const *yymsgp = YY_("syntax error");
        int yysyntax_error_status;
        yysyntax_error_status = YYSYNTAX_ERROR;
        if (yysyntax_error_status == 0)
          yymsgp = yymsg;
        else if (yysyntax_error_status == 1)
          {
            if (yymsg != yymsgbuf)
              YYSTACK_FREE (yymsg);
            yymsg = (char *) YYSTACK_ALLOC (yymsg_alloc);
            if (!yymsg)
              {
                yymsg = yymsgbuf;
                yymsg_alloc = sizeof yymsgbuf;
                yysyntax_error_status = 2;
              }
            else
              {
                yysyntax_error_status = YYSYNTAX_ERROR;
                yymsgp = yymsg;
              }
          }
        yyerror (yymsgp);
        if (yysyntax_error_status == 2)
          goto yyexhaustedlab;
      }
# undef YYSYNTAX_ERROR
#endif
    }



  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:

  /* Pacify compilers like GCC when the user code never invokes
     YYERROR and the label yyerrorlab therefore never appears in user
     code.  */
  if (/*CONSTCOND*/ 0)
     goto yyerrorlab;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYTERROR;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYTERROR)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  yystos[yystate], yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", yystos[yyn], yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

#if !defined yyoverflow || YYERROR_VERBOSE
/*-------------------------------------------------.
| yyexhaustedlab -- memory exhaustion comes here.  |
`-------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  /* Fall through.  */
#endif

yyreturn:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  yystos[*yyssp], yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
#if YYERROR_VERBOSE
  if (yymsg != yymsgbuf)
    YYSTACK_FREE (yymsg);
#endif
  return yyresult;
}
#line 510 "parser.y" /* yacc.c:1906  */


void yyerror(const char *error_string, ...) {
    va_list ap;
    int line_nmb(void);

    FILE *f = stdout;

    va_start(ap,error_string);

    ++synerrors;
	++errorflag;
	// fprintf(f, "synerrors = %d\n", synerrors);
    fprintf(f,"Error on line %d: ", lines);
    vfprintf(f,error_string,ap);
    fprintf(f,"\n");
    va_end(ap);
}

void check_ioredir(struct io_redir *optredir){
	/// Check the linked list for invalid redirects, if there are then raise an error
	struct io_redir *current = (struct io_redir *) malloc(sizeof(struct io_redir));
	current = optredir;
	int inflag = 0;
	int outflag = 0;
	int errflag = 0;	
	while(current != NULL)
	{
		if(inflag == 0 && current->redir_type == 0)
		{
			inflag = 1;
		}
		else if(current->redir_type == 0)
		{
			yyerror("Too many input redirects!");
		}

		if(outflag == 0 && (current->redir_type == 1 || current->redir_type == 2))
		{
			outflag = 1;
		}
		else if(current->redir_type == 1 || current->redir_type == 2)
		{
			yyerror("Too many output redirects!!");
		}

		if(errflag == 0 && (current->redir_type == 3 || current->redir_type == 4))
		{
			errflag = 1;
		}
		else if(current->redir_type == 3 || current->redir_type == 4)
		{
			yyerror("Too many error redirects!!!");
		}

		current = current->next;
	}
}

struct io_redir *find_iofile(struct io_redir *optredir, int type){
	/// Walk through the linked list searching for the given type of redirect
	struct io_redir *current = (struct io_redir *) malloc(sizeof(struct io_redir));
	current = optredir;
	while(current != NULL)
	{
		if(current->redir_type == type)
		{
			return(current);
		}
		current = current->next;
	}
	return(NULL);
}

void AssignVar(char *string){
	string = DelQuotes(string);
	char *substr = (char*)malloc(6);
	/// Check for PATH special case
	if (strlen(string) > 5)
	{
		memcpy(substr, string, 5);
	}
	if (DEBUG == 1) printf("substr : %s\n", substr);
	if (strcmp(substr, "PATH=") == 0)
	{
		int path_count = 1;         //number of tokens stored in path variable, separated by colons
		for (int i = 0; i < strlen(string); i++)
		{
			if (string[i] == ':')
			{
				if (path_count <= MAX_PATHS)
				{
					path_count++;
				}
				else
				{
					yyerror("Number of paths exceeds MAX_PATHS");
					break;
				}
			}
		}
	}

	/// Check for DEBUG special case
	if (strlen(string) > 6)
	{
		memcpy(substr, string, 6);
	}
	if (DEBUG == 1) printf("substr : %s\n", substr);
	if (strcmp(string, "DEBUG=") == 0)
	{
		DEBUG = 0;
	}
	else if (strlen(string) > 6 && strcmp(substr, "DEBUG=") == 0)
	{
		DEBUG = 1;
	}

	/// Separate variable into its name and value
	char *name = (char*)malloc(strlen(string));
	char *value = (char*)malloc(strlen(string));
	for (int i = 0; i < strlen(string); i++)
	{
		if (string[i] == '=')
		{
			memcpy(name, string, i);
			for (int j = i + 1; j < strlen(string); j++)
			{
				value[j - i - 1] = string[j];
			}
			break;
		}
	}

	/// Put variable into global array, if not already there, reassign if it is already there
	int isthere = 0;
	for (int i = 0; i < NEXT_OPEN_SPOT; i++)
	{
		if (DEBUG == 1) printf("vars[%d] : %s ?= %s\n", i, vars[i].name, name);
		if (strcmp(vars[i].name, name) == 0)
		{
			vars[i].value = value;
			isthere = 1;
			if (vars[i].is_exported == 1) putenv(string);
			break;
		}
	}
	if (isthere == 0 && NEXT_OPEN_SPOT < MAX_VARS)
	{
		vars[NEXT_OPEN_SPOT].name = name;
		vars[NEXT_OPEN_SPOT].value = value;
		vars[NEXT_OPEN_SPOT].is_exported = 0;
		NEXT_OPEN_SPOT++;
	}
	else if (NEXT_OPEN_SPOT == MAX_VARS)
	{
		yyerror("Maximum number of variables has been reached");
	}
}

void Prompt(){
	if (vars[1].value != NULL)
	{	// vars[1].name = "PROMPT"
		printf("%s", vars[1].value);
		fflush(stdout);
	}
}

char *DelQuotes(char *string){
	if (DEBUG == 1) printf("I'm in DelQuotes %s\n", string);
	for (int i = 0; i < strlen(string); i++)
	{
		if (string[i] == '\'' || string[i] == '\"')
		{
			for (int j = i; j < strlen(string) - 1; j++)
			{
				string[j] = string[j + 1];
			}
			string[strlen(string) - 2] = 0;
			break;
		}
	}
	if (DEBUG == 1) printf("string : %s\n", string);
	return string;
}

char *VarExpand(char *string){
	/// Check for single quotes
	// printf("string : %s\n", string);
	if (string[strlen(string) - 1] == '\'') return DelQuotes(string);
	int has_quotes = 0;
	for (int i = 0; i < strlen(string) - 1; i++)
	{
		if (string[i] == '\'')
		{
			has_quotes = 1;
			break;
		}
		else if (string[i] == '"')
		{
			break;
		}
	}
	if (has_quotes == 1) return DelQuotes(string);

	// printf("VarExpand string1 : %s\n", string);
	string = DelQuotes(string);
	// printf("VarExpand string2 : %s\n", string);
	char *result = (char*)malloc(strlen(string));
	int char_diff = 0;
    for (int i = 0; i < strlen(string); i++)
    {
		if (DEBUG == 1) printf("char_diff : %d\n", char_diff);
        if (string[i] == '$')
		{
			if (DEBUG == 1) printf("string[%d] = $\n", i);
			char *var = (char*)malloc(strlen(string));
			if (string[i + 1] == '{')
			{	/// Look for variable name inside brackets
				int j = i + 2;
				for (; j < strlen(string); j++)
				{
					if (string[j] == '}' || string[j] == '#' || string[j] == '%')
					{
						/// Logic for excluding patterns with # and %
						char *pattern = (char*)malloc(strlen(string));
						int num_symbols = 0;
						int beg_pattern = 0;
						int end_pattern = 0;
						if (string[j] == '#')
						{
							int k = j + 1;
							num_symbols += 1;
							beg_pattern += 1;
							if (string[j + 1] == '#')
							{
								k += 1;
								num_symbols += 1;
							}
							for (; k < strlen(string); k++)
							{
								if (string[k] == '}') break;
								else pattern[k - j - num_symbols] = string[k];
							}
						}
						else if (string[j] == '%')
						{
							int k = j + 1;
							num_symbols += 1;
							end_pattern += 1;
							if (string[j + 1] == '%')
							{
								k += 1;
								num_symbols += 1;
							}
							for (; k < strlen(string); k++)
							{
								if (string[k] == '}') break;
								else pattern[k - j - num_symbols] = string[k];
							}
						}
						if (DEBUG == 1) printf("pattern : %s\n", pattern);

						char *temp = mygetenv(var);
						char *value = (char *) malloc(strlen(temp));
						if (temp != NULL)
						{
							memcpy(value, temp, strlen(temp));		//copy the actual variable value
						}
						else
						{
							value = NULL;
						}
						if (DEBUG == 1) printf("test!!!!!!!!\n");

						/// If there was a pattern, need to remove it from the beginning or end
						if (pattern != NULL)
						{
							char *temp2 = VarExpand(pattern);
							pattern = realloc(pattern, strlen(temp2));
							memcpy(pattern, temp2, strlen(temp2));
							if (DEBUG == 1) printf("pattern (expanded) : %s\n", pattern);

							int pattern_match = 1;
							if (beg_pattern == 1)
							{
								for (int k = 0; k < strlen(pattern); k++)
								{
									if (pattern[k] != value[k])
									{
										pattern_match = 0;
										break;
									}
								}
								if (pattern_match == 1) value += strlen(pattern);
							}
							else if (end_pattern == 1)
							{
								for (int k = strlen(pattern) - 1, l = strlen(value) - 1; k >= 0; k--, l--)
								{
									if (DEBUG == 1) printf("pattern[%d] : %c, value[%d] : %c\n", k, pattern[k], l, value[l]);
									if (pattern[k] != value[l])
									{
										pattern_match = 0;
										break;
									}
								}
								if (pattern_match == 1) value[strlen(value) - strlen(pattern)] = 0;
							}
						}

						if (DEBUG == 1) printf("var : %s\n", var);
						if (DEBUG == 1) printf("var value : %s\n", value);
						if (value != NULL)
						{
							/// Resize result to take into account difference of size of ${VARIABLE} and its value
							result = realloc(result, strlen(string) + strlen(value) - 3 - num_symbols - strlen(var));
							for (int k = 0; k < strlen(value); k++)
							{
								result[k + i + char_diff] = value[k];
							}
							char_diff += strlen(value) - 3 - num_symbols - strlen(var);
							i += 2 + num_symbols + strlen(var) + strlen(pattern);
							break;
						}
						else
						{
							result[i + char_diff] = string[i];
							break;
						}
					}
					else
					{
						var[j - i - 2] = string[j];
					}
				}
				if (j == strlen(string))
				{
					yyerror("Braces not paired correctly");
				}
			}
			else
			{	/// Look for illegal chars to the right of the variable name
				for (int j = i + 1; j < strlen(string) + 1; j++)
				{
					if (isalpha(string[j]) == 0 && isdigit(string[j]) == 0 && string[j] != '_')
					{
						char *value = mygetenv(var);
						if (DEBUG == 1) printf("var : %s\n", var);
						if (DEBUG == 1) printf("var value : %s\n", value);
						if (value != NULL)
						{
							/// Resize result to take into account difference of size of $VARIABLE and its value
							result = realloc(result, strlen(string) + strlen(value) - 3 - strlen(var));
							for (int k = 0; k < strlen(value); k++)
							{
								result[k + i + char_diff] = value[k];
							}
							char_diff += strlen(value) - 1 - strlen(var);
							i += strlen(var);
							break;
						}
						else
						{
							result[i + char_diff] = string[i];
							break;
						}
					}
					else
					{
						var[j - i - 1] = string[j];
					}
				}
			}
		}
		else
		{
			result[i + char_diff] = string[i];
		}
    }
	return result;
}

char *mygetenv(char *name){
	if (DEBUG  == 1) printf("NEXT_OPEN_SPOT : %d\n", NEXT_OPEN_SPOT);
	for (int i = 0; i < NEXT_OPEN_SPOT; i++)
	{
		if (DEBUG  == 1) printf("vars[%d] : %s = %s\n", i, vars[i].name, vars[i].value);
		if (strcmp(vars[i].name, name) == 0)
		{
			return vars[i].value;
		}
	}
	return NULL;
}

void doForLoop(struct loopfor *myfor){
	/// Get the number of args
	struct args *current_arg = (struct args*) malloc(sizeof(struct args));
	current_arg = myfor->loopargs->next;
	int num_args = 1;
	while(current_arg != NULL)
	{
		if (num_args <= MAX_ARGS)
		{
			num_args++;
			current_arg = current_arg->next;
		}
		else
		{
			yyerror("Too many args!!");
			break;
		}
	}

	current_arg = myfor->loopargs;
	char *variable = (char *) malloc(strlen(myfor->variable));
	struct metacmdlist *current_cmd = (struct metacmdlist*) malloc(sizeof(struct metacmdlist));
	current_cmd = myfor->body;
	/// Do the loop
	for (int i = 0; i < num_args; i++)
	{
		/// Reassign the variable each time to the next arg
		memcpy(variable, myfor->variable, strlen(myfor->variable));
		variable = realloc(variable, 1 + strlen(current_arg->arg));
		strcat(variable, "=");
		strcat(variable, current_arg->arg);
		if (DEBUG == 1) printf("for var : %s\n", variable);
		AssignVar(variable);
		if (DEBUG == 1) printf("%s = %s\n", myfor->variable, mygetenv(myfor->variable));
		
		/// Do the command list
		while (current_cmd != NULL)
		{
			if (current_cmd->metacmd->cmd != NULL)
			{
				if (DEBUG == 1) printf("it's a command\n");
				struct command *cmdcpy = (struct command*) malloc(sizeof(struct command));
				memcpy(cmdcpy, current_cmd->metacmd->cmd, sizeof(struct command));
				cmdcpy->command = VarExpand2(cmdcpy->command);
				struct args *current = (struct args*) malloc(sizeof(struct args));
				memcpy(current, cmdcpy->pargs, sizeof(struct args));
				cmdcpy->pargs = current;
				while (current != NULL)
				{
					if (DEBUG == 1) printf("current1 = %s\n", current->arg);
					current->arg = VarExpand2(current->arg);
					if (DEBUG == 1) printf("current2 = %s\n", current->arg);
					// current->next = (struct args*) malloc(sizeof(struct args));
					current = current->next;
				}
				doline(cmdcpy, lines, errorflag, DEBUG);
			}
			else if (current_cmd->metacmd->forloop != NULL)
			{
				if (DEBUG == 1) printf("it's a for loop\n");
				doForLoop(current_cmd->metacmd->forloop);
			}
			else if (current_cmd->metacmd->whileloop != NULL)
			{
				if (DEBUG == 1) printf("it's a while loop\n");
				doWhileLoop(current_cmd->metacmd->whileloop);
			}
			else if (current_cmd->metacmd->var_assign != NULL)
			{
				if (DEBUG == 1) printf("it's a var assign\n");
				printf("string : %s\n", current_cmd->metacmd->var_assign);
				AssignVar(VarExpand2(current_cmd->metacmd->var_assign));
			}
			current_cmd = current_cmd->next;
		}

		/// Reset variable, current_cmd, and increment the arg
		memset(variable, 0, strlen(variable));
		current_cmd = myfor->body;
		current_arg = current_arg->next;
	}
}

void doWhileLoop(struct loopwhile *mywhile){

}

char *VarExpand2(char *string){
	char *result = (char*)malloc(strlen(string));
	int char_diff = 0;
    for (int i = 0; i < strlen(string); i++)
    {
		if (DEBUG == 1) printf("char_diff : %d\n", char_diff);
        if (string[i] == '$')
		{
			if (DEBUG == 1) printf("string[%d] = $\n", i);
			char *var = (char*)malloc(strlen(string));
			if (string[i + 1] == '{')
			{	/// Look for variable name inside brackets
				int j = i + 2;
				for (; j < strlen(string); j++)
				{
					if (string[j] == '}' || string[j] == '#' || string[j] == '%')
					{
						/// Logic for excluding patterns with # and %
						char *pattern = (char*)malloc(strlen(string));
						int num_symbols = 0;
						int beg_pattern = 0;
						int end_pattern = 0;
						if (string[j] == '#')
						{
							int k = j + 1;
							num_symbols += 1;
							beg_pattern += 1;
							if (string[j + 1] == '#')
							{
								k += 1;
								num_symbols += 1;
							}
							for (; k < strlen(string); k++)
							{
								if (string[k] == '}') break;
								else pattern[k - j - num_symbols] = string[k];
							}
						}
						else if (string[j] == '%')
						{
							int k = j + 1;
							num_symbols += 1;
							end_pattern += 1;
							if (string[j + 1] == '%')
							{
								k += 1;
								num_symbols += 1;
							}
							for (; k < strlen(string); k++)
							{
								if (string[k] == '}') break;
								else pattern[k - j - num_symbols] = string[k];
							}
						}
						if (DEBUG == 1) printf("pattern : %s\n", pattern);

						char *value = mygetenv(var);		//get the actual variable value

						/// If there was a pattern, need to remove it from the beginning or end
						if (pattern != NULL)
						{
							int pattern_match = 1;
							if (beg_pattern == 1)
							{
								for (int k = 0; k < strlen(pattern); k++)
								{
									if (pattern[k] != value[k])
									{
										pattern_match = 0;
										break;
									}
								}
								if (pattern_match == 1) value += strlen(pattern);
							}
							else if (end_pattern == 1)
							{
								for (int k = strlen(pattern) - 1, l = strlen(value) - 1; k >= 0; k--, l--)
								{
									if (DEBUG == 1) printf("pattern[%d] : %c, value[%d] : %c\n", k, pattern[k], l, value[l]);
									if (pattern[k] != value[l])
									{
										pattern_match = 0;
										break;
									}
								}
								if (pattern_match == 1) value[strlen(value) - strlen(pattern)] = 0;
							}
						}

						if (DEBUG == 1) printf("var : %s\n", var);
						if (DEBUG == 1) printf("var value : %s\n", value);
						if (value != NULL)
						{
							/// Resize result to take into account difference of size of ${VARIABLE} and its value
							result = realloc(result, strlen(string) + strlen(value) - 3 - num_symbols - strlen(var));
							for (int k = 0; k < strlen(value); k++)
							{
								result[k + i + char_diff] = value[k];
							}
							char_diff += strlen(value) - 3 - num_symbols - strlen(var);
							i += 2 + num_symbols + strlen(var) + strlen(pattern);
							break;
						}
						else
						{
							result[i + char_diff] = string[i];
							break;
						}
					}
					else
					{
						var[j - i - 2] = string[j];
					}
				}
				if (j == strlen(string))
				{
					yyerror("Braces not paired correctly");
				}
			}
			else
			{	/// Look for illegal chars to the right of the variable name
				for (int j = i + 1; j < strlen(string) + 1; j++)
				{
					if (isalpha(string[j]) == 0 && isdigit(string[j]) == 0 && string[j] != '_')
					{
						char *value = mygetenv(var);
						if (DEBUG == 1) printf("var : %s\n", var);
						if (DEBUG == 1) printf("var value : %s\n", value);
						if (value != NULL)
						{
							/// Resize result to take into account difference of size of $VARIABLE and its value
							result = realloc(result, strlen(string) + strlen(value) - 3 - strlen(var));
							for (int k = 0; k < strlen(value); k++)
							{
								result[k + i + char_diff] = value[k];
							}
							char_diff += strlen(value) - 1 - strlen(var);
							i += strlen(var);
							break;
						}
						else
						{
							result[i + char_diff] = string[i];
							break;
						}
					}
					else
					{
						var[j - i - 1] = string[j];
					}
				}
			}
		}
		else
		{
			result[i + char_diff] = string[i];
		}
    }
	return result;
}
